const products = [
  {
    name: "Red Bench",
    category: "People",
    price: 3.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.jpg",
      alt: "product image",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "Food",
    price: 93.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.1.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Man",
    category: "People",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.4.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "Landmark",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.5.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Red Bench",
    category: "People",
    price: 3.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "Food",
    price: 93.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.1.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Man",
    category: "People",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.4.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "Landmark",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.5.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Red Bench",
    category: "People",
    price: 3.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "Food",
    price: 93.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.1.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Man",
    category: "People",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.4.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "Landmark",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.5.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Red Bench",
    category: "People",
    price: 3.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Egg Balloon",
    category: "Food",
    price: 93.89,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.1.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Man",
    category: "People",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.4.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Architecture",
    category: "Landmark",
    price: 100,
    currency: "USD",
    image: {
      src: "/images/Rectangle 2.5.jpg",
      alt: "product image",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    name: "Samurai King Restling",
    category: "Pets",
    price: 101,
    currency: "USD",
    image: {
      src: "/images/featured.jpg",
      alt: "featured",
    },
    bestseller: false,
    featured: true,
    details: {
      dimensions: {
        width: 1020,
        height: 1020,
      },
      size: 15000,
      description:
        "Suspendisse faucibus est id leo finibus semper. Nam a consequat mi. Sed bibendum, est ut congue tincidunt, mauris ipsum commodo metus, id cursus eros augue sit amet turpis. Sed tincidunt eu diam eu fermentum. Pellentesque ornare bibendum magna, condimentum sodales felis varius in. Curabitur faucibus purus sit amet ullamcorper varius. Duis luctus ullamcorper enim eu pretium. Integer euismod augue in augue tincidunt, vel condimentum erat tincidunt. Cras pretium tincidunt purus, ac ornare sem ultrices ut.",
      recommendations: [
        {
          src: "/images/Rectangle 10.jpg",
          alt: "recommended image",
        },
        {
          src: "/images/Rectangle 10.1.jpg",
          alt: "recommended image",
        },
        {
          src: "/images/Rectangle 10.2.jpg",
          alt: "recommended image",
        },
      ],
    },
  },
];

export default products;
